
t002 <- t002 %>% select(ID, IN_BNP, BNP_YN, BNP_TYPE, BNP_VAL, IN_ALL, EX_ALL, STATUS)

t003 <- t003 %>% select(ID, RACE_WHITE, RACE_BLACK, RACE_ASIAN, RACE_OTHER, ETHNICITY)

t004 <- t004 %>% select(ID, EF)

t005 <- t005 %>%
  select(
    ID, CHF_HOSP, chfdc_dt3, MI, STROKE, CABG, PCI, ANGINA, COPD, ASTHMA, HTN, ICD,
    PACEMAKER, AFIB, DM
  )

t006 <- t006 %>% select(ID, nyha_class_cat, height, weight, HR, SBP, DBP)

t008 <- t008 %>% select(ID, CR_mgdl, gfr, NA_mmolL, K_mmolL, HB_gdL)

t010 <- t010 %>% select(ID, QRS_DUR, ECG_AFIB)

t011 <- t011 %>% select(ID, age_entry, GENDER, country, drug, CR_mgdL)

echobase <- echobase %>% select(ID, ef_tot)

t030 <- t030 %>% select(ID, term_dt_1)

t031 <- t031 %>% select(ID, dod1)

t079 <- t079 %>% select(ID, site_dt3, cec_dt3, DEATH_CAUSE, CV_DEATH, NONCV_DEATH)

dataout <- dataout %>% select(ID, death, cvd_death, time_death, hfhosp, time_hfhosp, primary_ep, time_primary_ep)

tcdata <- Reduce(
  function(...) {
    full_join(...,
      by = "ID"
    )
  },
  list(t002, echobase, t003, t004, t005, t006, t008, t010, t011, t030, t031, t079, dataout)
)

t007bymed <- t007bymed %>%
  filter(VISIT == "BASE")

combt007bymed <- t007bymed %>%
  filter(str_detect(MEDCAT_WHODDE, "COMBO - "))

combt007bymed <- bind_rows(combt007bymed %>% mutate(cr = 1), combt007bymed %>% mutate(cr = 2))
combt007bymed <- combt007bymed %>%
  mutate(MEDCAT_WHODDE = case_when(
    MEDCAT_WHODDE == "COMBO - ALISKIREN (OTHER CV ANTI-HTN) AND HCTZ (THIAZIDE DIURETIC)" & cr == 1 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - ALISKIREN (OTHER CV ANTIHTN) + VALSARTAN (ANGIOTENSIN RECEPTOR BLOCKER)" & cr == 1 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - AMLODIPINE (CALCIUM CHANNEL BLOCKER) + ATORVASTATIN (STATIN)" & cr == 1 ~ "CALCIUM CHANNEL BLOCKERS",
    MEDCAT_WHODDE == "COMBO - AMLODIPINE (CALCIUM CHANNEL BLOCKER) + ATORVASTATIN (STATIN)" & cr == 2 ~ "STATINS",
    MEDCAT_WHODDE == "COMBO - BENAZEPRIL (ACE INHIBITOR) + AMLODIPINE (CALCIUM CHANNEL BLOCKER)" & cr == 1 ~ "ACE INHIBITORS",
    MEDCAT_WHODDE == "COMBO - BENAZEPRIL (ACE INHIBITOR) + AMLODIPINE (CALCIUM CHANNEL BLOCKER)" & cr == 2 ~ "CALCIUM CHANNEL BLOCKERS",
    MEDCAT_WHODDE == "COMBO - CANDESARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 1 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - CANDESARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - ENALAPRIL (ACE INHIBITOR) + HYDROCHLOROTHIAZIDE (DIURETIC - THIAZIDE)" & cr == 1 ~ "ACE INHIBITORS",
    MEDCAT_WHODDE == "COMBO - ENALAPRIL (ACE INHIBITOR) + HYDROCHLOROTHIAZIDE (DIURETIC - THIAZIDE)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    # COMBO - GLIBENCLAMIDE (HYPOGLYCEMIC) + METFORMIN (HYPOGLYCEMIC)
    # COMBO - GLYBURIDE (HYPOGLYCEMIC) + METFORMIN (HYPOGLYCEMIC)
    MEDCAT_WHODDE == "COMBO - HYDRALAZINE (OTHER CV ANTIHTN) + ISOSORBIDE DINITRATE (LONG ACTING NITRATE)" & cr == 1 ~ "LONG ACTING NITRATE",
    MEDCAT_WHODDE == "COMBO - HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC) + TRIAMTERENE (POTASSIUM SPARING DIURETIC)" & cr == 1 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - IRBESARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 1 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - IRBESARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - LISINOPRIL (ACE INHIBITOR) + HYDROCHLOROTHIAZIDE (DIURETIC - THIAZIDE)" & cr == 1 ~ "ACE INHIBITORS",
    MEDCAT_WHODDE == "COMBO - LISINOPRIL (ACE INHIBITOR) + HYDROCHLOROTHIAZIDE (DIURETIC - THIAZIDE)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - LOSARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 1 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - LOSARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - LOSARTAN POTASSIUM (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 1 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - LOSARTAN POTASSIUM (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - LOVASTATIN (STATIN) + NIACIN (LIPID LOWERING - OTHER)" ~ "STATINS",
    MEDCAT_WHODDE == "COMBO - OLMESARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 1 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - OLMESARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - OTHER CV ANTI-HTN  (HYDRALAZINE) AND NITRATE (LONG ACTING)" ~ "LONG ACTING NITRATE",
    MEDCAT_WHODDE == "COMBO - PERINDOPRIL (ACE INHIBITOR) + INDAPAMIDE (DIURETIC - THIAZIDE)" & cr == 1 ~ "ACE INHIBITORS",
    MEDCAT_WHODDE == "COMBO - PERINDOPRIL (ACE INHIBITOR) + INDAPAMIDE (DIURETIC - THIAZIDE)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    # COMBO - PIOGLITAZONE (HYPOGLYCEMIC) + METFORMIN (HYPOGLYCEMIC)
    # COMBO - POTASSIUM (POTASSIUM) + MAGNESIUM (OTHER CV MED)
    # COMBO - ROSIGLITAZONE (HYPOGLYCEMIC) + GLIMEPERIDE (HYPOGLYCEMIC)
    MEDCAT_WHODDE == "COMBO - SIMVASTATIN  (STATIN) + EZETIMIBE (LIPID LOWERING - OTHER)" ~ "STATINS",
    # COMBO - SITAGLIPTIN (HYPOGLYCEMIC) + METFORMIN (HYPOGLYCEMIC)
    MEDCAT_WHODDE == "COMBO - TELMISARTAN (ANGIOTENSIN RECEPTOR BLOCKER) + HYDROCHLOROTHIAZIDE (DIURET" & cr == 1 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - TELMISARTAN (ANGIOTENSIN RECEPTOR BLOCKER) + HYDROCHLOROTHIAZIDE (DIURET" & cr == 2 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - TRIAMTERENE (DIURETIC - POTASSIUM SPARING) + HYDROCHLOROTHIAZIDE (DIURETIC - THIAZIDE)" ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - VALSARTAN (ANGIOTENSIN RECEPTOR BLOCKER) + AMLODIPINE (CALCIUM CHANNEL B" & cr == 1 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - VALSARTAN (ANGIOTENSIN RECEPTOR BLOCKER) + AMLODIPINE (CALCIUM CHANNEL B" & cr == 2 ~ "CALCIUM CHANNEL BLOCKERS",
    MEDCAT_WHODDE == "COMBO - VALSARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 1 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - VALSARTAN (ARB) + HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - ALISKIREN (OTHER CV ANTI-HTN) AND HCTZ (THIAZIDE DIURETIC)" & cr == 1 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - ALISKIREN (OTHER CV ANTIHTN) + VALSARTAN (ANGIOTENSIN RECEPTOR BLOCKER)" & cr == 2 ~ "ANGIOTENSIN RECEPTOR BLOCKERS",
    MEDCAT_WHODDE == "COMBO - HYDRALAZINE (OTHER CV ANTIHTN) + ISOSORBIDE DINITRATE (LONG ACTING NITRATE)" & cr == 2 ~ "LONG ACTING NITRATE",
    MEDCAT_WHODDE == "COMBO - HYDROCHLOROTHIAZIDE (THIAZIDE DIURETIC) + TRIAMTERENE (POTASSIUM SPARING DIURETIC)" & cr == 2 ~ "DIURETIC - THIAZIDE",
    MEDCAT_WHODDE == "COMBO - ALISKIREN (OTHER CV ANTI-HTN) AND HCTZ (THIAZIDE DIURETIC)" ~ "DIURETIC - THIAZIDE",
    TRUE ~ MEDCAT_WHODDE
  ))

t007bymed <- bind_rows(
  t007bymed %>%
    filter(str_detect(MEDCAT_WHODDE, "COMBO - ", negate = T)),
  combt007bymed
)

# koll <- t007bymed %>% count(MEDCAT_WHODDE)

medfunc <- function(meds, name) {
  tmp <- t007bymed %>%
    filter(MEDCAT_WHODDE %in% meds) %>%
    group_by(ID) %>%
    slice(1) %>%
    ungroup() %>%
    mutate(!!sym(name) := 1) %>%
    select(ID, !!sym(name))

  tcdata <<- left_join(tcdata, tmp, by = "ID") %>%
    mutate(!!sym(name) := ynfac(replace_na(!!sym(name), 0)))
}

medfunc(c("ACE INHIBITORS", "ANGIOTENSIN RECEPTOR BLOCKERS"), "rasi")
medfunc(c("BETA BLOCKERS"), "bbl")
medfunc(c("CALCIUM CHANNEL BLOCKERS"), "cbl")
medfunc(c("STATINS"), "statin")
medfunc(c("DIURETIC - CARBONIC ANHYDRASE INHIBITOR", "DIURETIC - LOOP", "DIURETIC - POTASSIUM SPARING", "DIURETIC - THIAZIDE"), "diuretics")
medfunc(c("DIURETIC - LOOP"), "loopdiuretics")


tcdata <- haven::zap_formats(tcdata)
tcdata <- haven::zap_label(tcdata)
