```{r outtabfunc, cache=cacheon}

modvarscoxbnp <- modvarscox[modvarscox != "ntprobnp_bnp_cat"]

modvarscr <- names(tcdataimp)[str_detect(names(tcdataimp), "_cr_")]
modvarscr <- modvarscr[str_detect(modvarscr, "prevhfhosp", negate = T)]
modvarscrkont <- tcdataimp %>%
  select(!!!syms(modvars)) %>%
  select(where(is.numeric))
modvarscr <- c(modvarscr, names(modvarscrkont))

survfunc <- function(time, event, eventcr = NULL, hospvarcr = NULL, eventname, hospvar, rep = FALSE, repevent = NULL) {
  levsh <- levels(tcdata %>% pull(!!sym(hospvar)))
  nlevsh <- length(levsh)

  out <- data.frame(matrix(NA, ncol = nlevsh + 2, nrow = 5))

  out[1, 1] <- eventname
  colnames(out) <- c("Outcome", "Model", levsh)

  ## incidence rate
  out[1, 2] <- "No events, sum py, incidence rate/100py (95% CI)"

  if (!rep) {
    ev <- tcdata %>%
      group_by(!!sym(hospvar)) %>%
      summarise(
        ev = sum(!!sym(event) == "Yes"),
        .groups = "rowwise"
      )
  }
  if (rep) {
    ev <- tcdata %>%
      group_by(!!sym(hospvar)) %>%
      summarise(
        ev = sum(!!sym(event)),
        .groups = "rowwise"
      )
  }
  s <- tcdata %>%
    group_by(!!sym(hospvar)) %>%
    summarise(
      s = sum(!!sym(time)),
      .groups = "rowwise"
    )
  r <- pois.exact(x = ev$ev, pt = s$s / 100)

  out[1, 3:(nlevsh + 2)] <- paste0(
    ev$ev, ", ",
    fn(s$s, dig = 0), ", ",
    fn(r$rate, dig = 1), " (",
    fn(r$lower, dig = 1), "-",
    fn(r$upper, dig = 1), ")"
  )

  if (!rep) {
    # cox regressions
    ## crude
    out[2, 2] <- "Crude HR (95% CI), p-value"

    ## crude
    mod <- summary(coxph(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ ", hospvar)),
      data = tcdata
    ))

    out[2, 3:(nlevsh + 2)] <- c("ref", paste0(
      fn(mod$conf.int[1:(nlevsh - 1), 1], dig = 2),
      " (", fn(mod$conf.int[1:(nlevsh - 1), 3], dig = 2),
      "-", fn(mod$conf.int[1:(nlevsh - 1), 4], dig = 2), "), ",
      fn(mod$coef[1:(nlevsh - 1), 5], dig = 3, p = TRUE)
    ))

    ## adjusted
    out[3, 2] <- "Adjusted HR (95% CI), p-value"

    mod <- summary(coxph(formula(paste0(
      "Surv(", time, ",", event, "=='Yes') ~ ", hospvar, " + ",
      paste(modvarscox, collapse = " + ")
    )),
    data = tcdataimp
    ))

    out[3, 3:(nlevsh + 2)] <- c("ref", paste0(
      fn(mod$conf.int[1:(nlevsh - 1), 1], dig = 2),
      " (", fn(mod$conf.int[1:(nlevsh - 1), 3], dig = 2),
      "-", fn(mod$conf.int[1:(nlevsh - 1), 4], dig = 2), "), ",
      fn(mod$coef[1:(nlevsh - 1), 5], dig = 3, p = TRUE)
    ))

    ## adjusted excluding ntprobnp/bnp

    out[4, 2] <- "Adjusted (excl NT-proBNP/BNP) HR (95% CI), p-value"

    mod <- summary(coxph(formula(paste0(
      "Surv(", time, ",", event, "=='Yes') ~ ", hospvar, " + ",
      paste(modvarscoxbnp, collapse = " + ")
    )),
    data = tcdataimp
    ))

    out[4, 3:(nlevsh + 2)] <- c("ref", paste0(
      fn(mod$conf.int[1:(nlevsh - 1), 1], dig = 2),
      " (", fn(mod$conf.int[1:(nlevsh - 1), 3], dig = 2),
      "-", fn(mod$conf.int[1:(nlevsh - 1), 4], dig = 2), "), ",
      fn(mod$coef[1:(nlevsh - 1), 5], dig = 3, p = TRUE)
    ))

    # Sens analyses F&G

    out[5, 2] <- "Adjusted, F&G, HR (95% CI), p-value"

    mod <- summary(crr(
      tcdataimp %>% pull(!!sym(time)),
      tcdataimp %>% pull(!!sym(eventcr)),
      tcdataimp %>% select(!!!syms(c(hospvarcr, modvarscr))),
      failcode = 1, cencode = 0
    ))

    out[5, 3:(nlevsh + 2)] <- c("ref", paste0(
      fn(mod$conf.int[1:(nlevsh - 1), "exp(coef)"], dig = 2),
      " (", fn(mod$conf.int[1:(nlevsh - 1), "2.5%"], dig = 2),
      "-", fn(mod$conf.int[1:(nlevsh - 1), "97.5%"], dig = 2), ") ",
      fn(mod$coef[1:(nlevsh - 1), "p-value"], dig = 3, p = TRUE)
    ))
  }

  if (rep) {
    # PWP
    ## crude
    out[2, 2] <- "Crude, PWP, HR (95% CI), p-value"

    mod <- summary(coxph(formula(paste0("Surv(timestart, timestop, ", repevent, " == 'Yes') ~ ", hospvar, " + cluster(ID) + strata(eventno)")),
      data = tcdataimprec
    ))

    out[2, 3:(nlevsh + 2)] <- c("ref", paste0(
      fn(mod$conf.int[1:(nlevsh - 1), 1], dig = 2),
      " (", fn(mod$conf.int[1:(nlevsh - 1), 3], dig = 2),
      "-", fn(mod$conf.int[1:(nlevsh - 1), 4], dig = 2), "), ",
      fn(mod$coef[1:(nlevsh - 1), "Pr(>|z|)"], dig = 3, p = TRUE)
    ))


    ## adjusted
    out[3, 2] <- "Adjusted, PWP, HR (95% CI), p-value"

    mod <- summary(coxph(formula(paste0(
      "Surv(timestart, timestop, ", repevent, " == 'Yes') ~ ",
      hospvar, " + ",
      paste(modvarscox, collapse = " + "),
      " + cluster(ID) + strata(eventno)"
    )),
    data = tcdataimprec
    ))

    out[3, 3:(nlevsh + 2)] <- c("ref", paste0(
      fn(mod$conf.int[1:(nlevsh - 1), 1], dig = 2),
      " (", fn(mod$conf.int[1:(nlevsh - 1), 3], dig = 2),
      "-", fn(mod$conf.int[1:(nlevsh - 1), 4], dig = 2), "), ",
      fn(mod$coef[1:(nlevsh - 1), "Pr(>|z|)"], dig = 3, p = TRUE)
    ))

    ## adjusted excl nt
    out[4, 2] <- "Adjusted (excl NT-proBNP/BNP), PWP, HR (95% CI), p-value"

    mod <- summary(coxph(formula(paste0(
      "Surv(timestart, timestop, ", repevent, " == 'Yes') ~ ",
      hospvar, " + ",
      paste(modvarscoxbnp, collapse = " + "),
      " + cluster(ID) + strata(eventno)"
    )),
    data = tcdataimprec
    ))

    out[4, 3:(nlevsh + 2)] <- c("ref", paste0(
      fn(mod$conf.int[1:(nlevsh - 1), 1], dig = 2),
      " (", fn(mod$conf.int[1:(nlevsh - 1), 3], dig = 2),
      "-", fn(mod$conf.int[1:(nlevsh - 1), 4], dig = 2), "), ",
      fn(mod$coef[1:(nlevsh - 1), "Pr(>|z|)"], dig = 3, p = TRUE)
    ))

    # neg binomial regression

    ## adjusted
    mod <- glm.nb(formula(paste0(
      event, " ~ ", hospvar, " + ",
      paste(modvarscox, collapse = " + "), " + offset(log(", time, "))"
    )),
    data = tcdataimp
    )

    smod <- summary(mod)
    out[5, 2] <- "Adjusted, NBR, IRR (95% CI), p-value"
    out[5, 3:(nlevsh + 2)] <- c("ref", paste0(
      fn(exp(smod$coefficients[2:(nlevsh), 1]), dig = 2),
      " (", fn(exp(smod$coefficients[2:(nlevsh), 1] - global_z05 * smod$coefficients[2:(nlevsh), 2]), dig = 2),
      "-", fn(exp(smod$coefficients[2:(nlevsh), 1] + global_z05 * smod$coefficients[2:(nlevsh), 2]), dig = 2), "), ",
      fn(smod$coefficients[2:(nlevsh), 4], dig = 3, p = TRUE)
    ))
  }
  return(out)
}

survfunc2 <- function(hospvar2, hospvarcr2) {
  s1 <- survfunc(
    time = "outtime_cvd",
    event = "out_cvdhfhno",
    eventname = "CVD/total HFH",
    hospvar = hospvar2,
    rep = TRUE,
    repevent = "out_cvdhfh"
  )
  s12 <- survfunc(
    time = "outtime_cvd",
    event = "out_cvdsenshfhno",
    eventname = "CVD/total HFH (unknown death as Non-CVD)",
    hospvar = hospvar2,
    rep = TRUE,
    repevent = "out_cvdsenshfh"
  )
  s2 <- survfunc(
    time = "outtime_cvd",
    event = "out_cvd",
    eventcr = "out_cvd_cr",
    eventname = "CVD",
    hospvar = hospvar2,
    hospvarcr = hospvarcr2
  )
  s3 <- survfunc(
    time = "outtime_cvd",
    event = "out_hfhno",
    eventname = "Total HFH",
    hospvar = hospvar2,
    rep = TRUE,
    repevent = "out_hfh"
  )
  s4 <- survfunc(
    time = "outtime_hfh",
    event = "out_cvdhfh",
    eventcr = "out_cvdhfh_cr",
    eventname = "CVD/first HFH",
    hospvar = hospvar2,
    hospvarcr = hospvarcr2
  )
  s5 <- survfunc(
    time = "outtime_hfh",
    event = "out_hfh",
    eventcr = "out_hfh_cr",
    eventname = "First HFH",
    hospvar = hospvar2,
    hospvarcr = hospvarcr2
  )

  outall <- rbind(
    s1, s12, s2, s3, s4, s5
  ) # %>%
  # mutate(across(c(Outcome, Model), sanitize_text))

  return(outall)
}
```

```{r outtabcat, cache=cacheon, dependson="outtabfunc"}
out <- survfunc2(
  hospvar2 = "prevhfhosp_cat",
  hospvarcr2 = c(
    "prevhfhosp_cat_cr_Inmhospital",
    "prevhfhosp_cat_cr_HFH1m30d",
    "prevhfhosp_cat_cr_HFH31m90d",
    "prevhfhosp_cat_cr_HFH91m180d",
    "prevhfhosp_cat_cr_HFH181m365d",
    "prevhfhosp_cat_cr_HFHover365d"
  )
)

write.xlsx(out, paste0("./output/tabs/Association between previous HFH groups and outcomes_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

default_kable(out,
  # font_size = 6,
  caption = "Association between previous HFH groups and outcomes"
) %>%
  landscape()
```

```{r outtab, cache=cacheon, dependson="outtabfunc"}

out <- survfunc2(hospvar2 = "prevhfhosp", hospvarcr2 = "prevhfhosp_cr_Yes")

write.xlsx(out, paste0("./output/tabs/Association between previous HFH and outcomes_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

default_kable(out,
  # font_size = 3#,
  caption = sanitize_text("Association between previous HFH and outcomes")
)
```
