
```{r splinefunc, cache=cacheon}

mytermplot <- function(mod, xlab = "Time since previous HHF (months)", ylab = "Adjusted HR (95% CI)",
                       yaxismy = c(0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5)) {
  cexmy <- 1.2

  zz <- termplot(mod, se = TRUE, plot = FALSE, terms = 1)

  # HR = 1 at median https://cran.r-project.org/web/packages/survival/vignettes/splines.pdf
  hfterm <- zz$chfdc_dt3num

  med <- median(tcdataimp$chfdc_dt3num, na.rm = T)
  center <- with(hfterm, y[x == med])

  lci <- zz$chfdc_dt3num$y - 1.96 * zz$chfdc_dt3num$se - center
  uci <- zz$chfdc_dt3num$y + 1.96 * zz$chfdc_dt3num$se - center

  # c(bottom, left, top, right)
  par(mar = c(5, 4, 2, 2) + 0.1)

  plot(hfterm$x, hfterm$y - center,
    type = "n", axes = F,
    xaxs = "i", yaxs = "i", xlim = c(0, 366), ylim = log(c(min(yaxismy), max(yaxismy))),
    xlab = xlab, ylab = ylab, cex.lab = cexmy
  )

  polygon(
    x = c(rev(hfterm$x), hfterm$x),
    y = c(rev(uci), lci),
    col = global_cols[8],
    border = NA
  )

  axis(1, seq(0, 12, 1) * 30.5, seq(0, 12, 1), cex.axis = cexmy)
  axis(2, log(yaxismy), yaxismy, las = 2, cex.axis = cexmy)

  lines(hfterm$x, hfterm$y - center, lwd = 3, col = global_cols[3])

  abline(h = 0, col = 1, lty = 3, lwd = 2)

  rug(tcdataimp$chfdc_dt3num)

  invisible(zz)
}

splinefunc <- function(time = NULL, event) {
  if (!is.null(time)) {
    mod <- coxph(formula(paste0(
      "Surv(", time, ",", event, " == 'Yes') ~ ns(chfdc_dt3num, df = 4) + ",
      paste(modvarscox, collapse = " + ")
    )),
    data = tcdataimp
    )
  } else {
    mod <- coxph(formula(paste0(
      "Surv(timestart, timestop, ", event, " == 'Yes') ~ ns(chfdc_dt3num, df = 4) + ",
      paste(modvarscox, collapse = " + "),
      " + cluster(ID) + strata(eventno)"
    )),
    data = tcdataimprec
    )
  }
  mytermplot(mod)
}
```

```{r scvdrephfh, fig.cap="Spline CVD/total HHF", cache=cacheon, dependson="splinefunc", fig.width=8, fig.height=7}
splinefunc(
  event = "out_cvdhfh"
)
```

```{r scvd, fig.cap="Spline CVD", cache=cacheon, dependson="splinefunc", fig.width=8, fig.height=7}
splinefunc(
  time = "outtime_cvd",
  event = "out_cvd"
)
```

```{r srephfh, fig.cap="Spline total HHF", cache=cacheon, dependson="splinefunc", fig.width=8, fig.height=7}
splinefunc(
  event = "out_hfh"
)
```

```{r scvdhfh1, fig.cap="Spline CVD/first HHF", cache=cacheon, dependson="splinefunc", fig.width=8, fig.height=7}
splinefunc(
  time = "outtime_hfh",
  event = "out_cvdhfh"
)
```
  
```{r shfh1, fig.cap="Spline first HHF", cache=cacheon, dependson="splinefunc", fig.width=8, fig.height=7}
splinefunc(
  time = "outtime_hfh",
  event = "out_hfh"
)
```
